dist: xenial
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
    update: true
git:
  depth: false
language: java
jdk: oraclejdk12
before_script:
  - sqlite3 -version
  - make -version
  - make clean-all
  - make sqlite-db-build
  - make sqlite-db-populate-dev-dataset
script: "./gradlew test"
after_success:
    - "./gradlew jacocoTestReport"
    - bash <(curl -s https://codecov.io/bash)
