name: Standard Tests
on: [push, pull_request, workflow_dispatch] #workflow_dispatch works only if its active in the main branch
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setting up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt' #using a specific distribution of jdk11 (AdoptOpenJDK)

    - name: Setting up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Setting up Gradle Wrapper
      run: "gradle wrapper"

    - name: Validating Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setting up the SQLite database and Make
      run: | 
        sqlite3 -version
        make -version
        make clean-all
        make sqlite-db-build
        make sqlite-db-populate-dev-dataset

    - name: Running Tests
      run: "./gradlew test"

    - name: After Success Submitting Code Coverage
      run: | #jacocoTestReport is for testing code coverage, submits the last report to the link
        ./gradlew jacocoTestReport
        bash <(curl -s https://codecov.io/bash)